2018-05-17 14:12:48.218 +02:00 [WRN] The LINQ expression 'where {from Int32 o in __ids_0 where ([o] == [e].Id) select [o] => Any()}' could not be translated and will be evaluated locally.
2018-05-17 14:12:48.374 +02:00 [WRN] The LINQ expression 'where ([o] == [e].Id)' could not be translated and will be evaluated locally.
2018-05-17 14:12:48.378 +02:00 [WRN] The LINQ expression 'Any()' could not be translated and will be evaluated locally.
2018-05-17 15:05:47.787 +02:00 [ERR] An unhandled exception has occurred while executing the request
System.ArgumentNullException: Value cannot be null.
Parameter name: providerKey
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByLoginAsync(String loginProvider, String providerKey)
   at IM.TCM.Api.Controllers.UsersController.<PostUser>d__8.MoveNext() in C:\Users\h7707132\source\repos\IM.TCM\IM.TCM.Api\Controllers\UsersController.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-17 15:05:48.719 +02:00 [ERR] An unhandled exception has occurred while executing the request
System.ArgumentNullException: Value cannot be null.
Parameter name: providerKey
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByLoginAsync(String loginProvider, String providerKey)
   at IM.TCM.Api.Controllers.UsersController.<PostUser>d__8.MoveNext() in C:\Users\h7707132\source\repos\IM.TCM\IM.TCM.Api\Controllers\UsersController.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-05-17 16:52:52.185 +02:00 [WRN] The LINQ expression 'where {from Int32 o in __ids_0 where ([o] == [e].Id) select [o] => Any()}' could not be translated and will be evaluated locally.
2018-05-17 16:52:52.272 +02:00 [WRN] The LINQ expression 'where ([o] == [e].Id)' could not be translated and will be evaluated locally.
2018-05-17 16:52:52.287 +02:00 [WRN] The LINQ expression 'Any()' could not be translated and will be evaluated locally.
2018-05-17 17:29:22.821 +02:00 [WRN] The LINQ expression 'where {from Int32 o in __ids_0 where ([o] == [e].Id) select [o] => Any()}' could not be translated and will be evaluated locally.
2018-05-17 17:29:22.882 +02:00 [WRN] The LINQ expression 'where ([o] == [e].Id)' could not be translated and will be evaluated locally.
2018-05-17 17:29:22.891 +02:00 [WRN] The LINQ expression 'Any()' could not be translated and will be evaluated locally.
2018-05-17 17:30:54.611 +02:00 [WRN] The LINQ expression 'where {from Int32 o in __ids_0 where ([o] == [e].Id) select [o] => Any()}' could not be translated and will be evaluated locally.
2018-05-17 17:30:54.701 +02:00 [WRN] The LINQ expression 'where ([o] == [e].Id)' could not be translated and will be evaluated locally.
2018-05-17 17:30:54.747 +02:00 [WRN] The LINQ expression 'Any()' could not be translated and will be evaluated locally.
2018-05-17 17:52:06.537 +02:00 [WRN] The LINQ expression 'where {from Int32 o in __ids_0 where ([o] == [e].Id) select [o] => Any()}' could not be translated and will be evaluated locally.
2018-05-17 17:52:06.607 +02:00 [WRN] The LINQ expression 'where ([o] == [e].Id)' could not be translated and will be evaluated locally.
2018-05-17 17:52:06.616 +02:00 [WRN] The LINQ expression 'Any()' could not be translated and will be evaluated locally.
